htw_photoweb_homepage:
    pattern:  /
    defaults: { _controller: HTWPhotoWebBundle:Default:index }


photo:
    resource: 	"@HTWPhotoWebBundle/Controller/PhotoController.php"
    prefix: 	/photo
    type:     	annotation

static:
    resource: 	"@HTWPhotoWebBundle/Controller/StaticPageController.php"
    type:     	annotation

user:
    resource: 	"@HTWPhotoWebBundle/Controller/UserController.php"
    prefix: 	/users
    type:     	annotation

myarea:
    resource: 	"@HTWPhotoWebBundle/Controller/MyAreaController.php"
    prefix: 	/myarea
    type:     	annotation

search:
    resource:   "@HTWPhotoWebBundle/Controller/SearchController.php"
    prefix:     /search
    type:       annotation
