htw_photo_web_homepage:
    pattern:  /
    defaults: { _controller: HTWPhotoWebBundle:Default:index }

htw_photo_web_photo_upload:
    pattern: /photo/upload
    defaults: { _controller: HTWPhotoWebBundle:Photo:upload }